### ISSUE TITLE
Ezra, People Search option error.

### ISSUE THREAD

**Issue by MurderHoof** [Ezra-Hubbard/Ezra-Hubbard.github.io#15]
Hi there,

There's an error message that pops up whenever I search for an actor on either the PC or Android devices, so just wondering whether you could fix it with your next update.

Thank you for what you've created and for all that you do, and many thanks in advance for also being available to help in matters like these.

ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--

- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!

Error Type: <class 'NameError'>

Error Contents: name 'ls' is not defined

Traceback (most recent call last):

File "C:\Users\mania\AppData\Roaming\Kodi\addons\plugin.video.ezra\resources\lib\ezra.py", line 4, in <module>

routing(argv[2])

File "C:\Users\mania\AppData\Roaming\Kodi\addons\plugin.video.ezra\resources\lib\modules\router.py", line 297, in routing

get_search_term(params)

File "C:\Users\mania\AppData\Roaming\Kodi\addons\plugin.video.ezra\resources\lib\modules\history.py", line 45, in get_search_term

return person_search(query)

File "C:\Users\mania\AppData\Roaming\Kodi\addons\plugin.video.ezra\resources\lib\indexers\people.py", line 41, in person_search

kwargs = {'items': json.dumps(list_items), 'heading': ls(32036), 'enumerate': 'false', 'multi_choice': 'false', 'multi_line': 'false'}

NameError: name 'ls' is not defined

-->End of Python script error report<--

**Comment by umbrellaplug** [comment]
Did a pull request to resolve this. Once developer can look over the fix and approve the request the issue should be resolved for you.

**Comment by Ezra-Hubbard** [comment]
https://github.com/Ezra-Hubbard/plugin.video.ezra/commit/7f2ca44c74fe2de71455cd403c9b86172d2e11d3
